version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=todo-list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - todo_net
    ports:
      - "5432:5432"
    volumes: 
      - ./db/postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - todo_net
    ports:
      - 5050:80
    volumes:
       - ./db/pgadmin_data:/var/lib/pgadmin

  api:
    container_name: api_service
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    networks:
      - todo_net
    volumes:
      - ./api/src:/app/src
      - ./api/prisma:/app/prisma
    ports:
      - "8000:8000"

networks:
  todo_net:
    driver: bridge